// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "test": "test lang",
  "AUTH": {
    "SIGN_IN": "Sign in",
    "SIGN_UP": "Sign up",
    "SIGN_UP_NEW_ACCOUNT": "Sign up your new account",
    "SIGN_UP_WITH": "Sign up with {serviceName}",
    "SIGN_IN_WITH": "Sign in with {serviceName}",
    "SIGN_IN_SUCCESSFULLY": "Authorization was successfully"
  },
  "HEADER_MENU": {
    "EXIT": "Exit",
    "SETTINGS": "Settings"
  },
  "NOT_FOUND": {
    "TITLE": "Page not found"
  },
  "COMMON": {
    "SOMETHING_ERROR": "Something went wrong...",
    "LOADING": "Loading. Wait a few time..."
  }
};
export default messages;