// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "test": "test lang",
  "AUTH": {
    "SIGN_IN": "Sign in",
    "SIGN_UP": "Sign up"
  }
};
export default messages;