import { ReactNode } from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import {Header} from "@repo/components/widgets";

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header className={'text-6xl'} />
        <div className={'bg-black text-white text-4xl'}>123</div>
        {children}
      </body>
    </html>
  );
}
