import { ReactNode } from 'react';
import clsx from 'clsx';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Layout } from '@/modules/layout';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={clsx(
          `${geistSans.variable} ${geistMono.variable}`,
          'dark bg-background text-foreground',
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
